### ISSUE TITLE
Enregistrer / Restaurer une configuration initiale de l'application

### ISSUE THREAD

**Issue by Eveol** [baal-ilion/rallye.schema#11]

**Comment by baal-ilion** [comment]
Ajout d'un menu "Import / Export du paramétrage".

![image](https://user-images.githubusercontent.com/59480482/76790549-5a529f00-67bf-11ea-9819-9dd6e0705c19.png)

Le bouton "Exporter" permet de télécharger un fichier zip qui contient le paramétrage actuel.
Il est possible de remplacer le paramétrage actuel en sélectionnant un fichier zip précédemment téléchargé.
