### ISSUE TITLE
Retour d'information de lAPI

### ISSUE THREAD

**Issue by rirethy** [baal-ilion/rallye.schema#16]
actuellement sauf erreur de ma part, en réponse à un envoi de JSON pour une correction d’étape, l'API nous retourne le JSON envoyé.
C'est peut être normal et voulu, mais dans ce cas comment détecter une erreur en fonction du retour de l'API ?
En fait, y-a-t-il moyen de détecter qu'une erreur s'est produite ?

**Comment by baal-ilion** [comment]
L'api stocke le message en base et renvoie ce qu'il en a compris. Si une erreur survient dans le décodage ou le stockage tu auras un retour 500 (ou autre) avec l'erreur, sinon tu as un retour 200 avec ce qui a été compris du message. le reste du traitement est asynchrone donc tu ne peut pas avoir d'info en retour de la requête.

**Comment by rirethy** [comment]
OK, alors, ça me va :-)
